log('a'.indent(2) === '  a');
log('a'.indent(2, '	') === '		a');
log('a\na'.indent(2) === '  a\n  a');
log('a'.indent(0) === 'a');
log('a'.wrap('t') === 'tat');
log('a'.wrap('t', 's') === 'tas');
log('e'.wrap(9) === '9e9');
log('test'.extract(/^(t)e(st)$/) === 't');
log('test'.extract(/^(t)e(st)$/, 2) === 'st');
log('test'.capitalize() === 'Test');
log('テスト'.convertToUnicode() === 'ƹ');
log('テスト'.convertToUnicode('Shift_JIS') === 'ﾆｹﾈ');
log('テスト'.convertToUnicode('EUC-JP') === '胴');
log('テスト'.convertToUnicode('iso-2022-jp') === '���');
log('テスト'.convertFromUnicode() === 'ãã¹ã');
log('テスト'.convertFromUnicode('Shift_JIS') === 'eXg');
log('テスト'.convertFromUnicode('EUC-JP') === '¥Æ¥¹¥È');
log('テスト'.convertFromUnicode('iso-2022-jp') === '$B%F%9%H');
log('%3A%40%2F%23%3F%3D%2B%26%3B%2C%24%22%E3%83%86%E3%82%B9%E3%83%88'.unEscapeURI() === ':@/#?=+&;,$"テスト');
log('%3A%40%2F%23%3F%3D%2B%26%3B%2C%24%22%E3%83%86%E3%82%B9%E3%83%88'.unEscapeURI() === decodeURIComponent('%3A%40%2F%23%3F%3D%2B%26%3B%2C%24%22%E3%83%86%E3%82%B9%E3%83%88'));
log('abcdefghijklmnopqrstuvwxyz0123456789-_.!~*\'()'.unEscapeURI() === 'abcdefghijklmnopqrstuvwxyz0123456789-_.!~*\'()');
log('%A5%C6%A5%B9%A5%C8'.unEscapeURI() === '%A5%C6%A5%B9%A5%C8');
log('%A5%C6%A5%B9%A5%C8'.unEscapeURI('EUC-JP') === 'テスト');
log('a<!--test-->a'.trimTag() === 'aa');
log('<div>a</div>'.trimTag() === 'a');
log('<div>a<p>a</div>'.trimTag() === 'aa');
log('<!--test--><div>a</div>'.trimTag() === 'a');
log('<!--test-->\n<div>a</div>'.trimTag() === '\na');
log('123abc'.charLength === 6);
log('吉野家'.charLength === 3);
log('𠮷野家'.charLength === 3);
