log(Models['Yahoo JMA'].hiraganaToKatakana('aiueo') === 'aiueo');
log(Models['Yahoo JMA'].hiraganaToKatakana('あいうえお') === 'アイウエオ');
log(Models['Yahoo JMA'].hiraganaToKatakana('かきくけこ') === 'カキクケコ');
log(Models['Yahoo JMA'].kanaToRoma('aiueo') === 'aiueo');
log(Models['Yahoo JMA'].kanaToRoma('あいうえお') === 'aiueo');
log(Models['Yahoo JMA'].kanaToRoma('かきくけこ') === 'kakikukeko');
log(Models['Yahoo JMA'].kanaToRoma('アイウエオ') === 'aiueo');
log(Models['Yahoo JMA'].kanaToRoma('カキクケコ') === 'kakikukeko');
log(Models['Yahoo JMA'].katakanaTable.get('ア') === 'a');
